config/routes.rb
Tessaanntaylor::Application.routes.draw do
  root "pages#index"
  
  get '/dots', to: 'pages#dots'
  get '/font', to: 'pages#font'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_filter :set_request_vars
  
  
  private
  
  def set_request_vars
    @action     = action_name
    @controller = controller_name
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
  
  def dots
  end

  def font
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def google_analytics
    if (ENV['RAILS_ENV'] == 'production')
      return javascript_tag("(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-48896181-1', 'tessaanntaylor.com');
      ga('send', 'pageview');")
    end
  end
  
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
<header>
	<ul>
		<li><%= link_to('home', root_path, :class => "home")  %></li>
		<li><%= link_to('dots', dots_path, :class => "dots")  %></li>
		<li><%= link_to('font', font_path, :class => "font")  %></li>
		<li><%= link_to('blog', 'http://blog.tessaanntaylor.com')  %></li>
	</ul>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tessa Ann Taylor</title>

	<!-- Meta Tags -->
	<meta name="keywords" content="tessa ann taylor software codergirl c0dergirl c0d3rgirl" />
	<meta name="description" content="" />

	<!-- FB Meta Tags -->
	<meta property="og:title" content="Tessa Ann Taylor" />
	<meta property="og:type" content="website" />
	<meta property="og:description" content="">
	<meta property="og:url" content="<%= root_url %>" />
	<meta property="og:image" content="<%= asset_url('feather.png') %>" />
	<meta property="og:site_name" content="" />

	<!-- Mobile Tags -->
	<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no" />

	<!-- CSS -->
  <%= stylesheet_link_tag    "application", media: "all" %>
  
	<!-- JS -->
	<%= javascript_include_tag "http://code.jquery.com/jquery-1.10.2.min.js" %>
	<script type="text/javascript">$(document).bind("mobileinit", function(){$.extend(  $.mobile , {autoInitializePage: false})});</script>
	<%= javascript_include_tag "http://code.jquery.com/mobile/1.3.2/jquery.mobile-1.3.2.min.js" %>
	<%= javascript_include_tag "application" %>

  <%= csrf_meta_tags %>

	<!-- Google Analytics -->
	<%= google_analytics %>
	
</head>
<body class="<%= @controller %> <%= @action %>">
	
	<%= render 'layouts/header' %>

	<%= yield %>

</body>
</html>

app/views/pages/dots.html.erb
<div class="dots-container"></div>
<a href="#" class="redraw">Again?</a>

app/views/pages/font.html.erb
<div class="font-container"></div>

app/views/pages/index-old.html.erb
<h1>Tessa Ann Taylor,</h1>
<h2>The Code and Styles of</h2>

<div class="custom-scroll">
	
	<div class="scrollbar">
		<span class="current"></span>
	</div>

	<div class="scroll-content elements">
		
		<%= link_to '', "http://coapp.co", :alt => "Co", :class => "element co", :target => "_blank" %>
		<hr class="y">
		<%= link_to '', "http://beautifully.unapologeticallycss.com", :alt => "Beautifully, Unapologetically CSS", :class => "element iphone", :target => "_blank" %>
		<hr class="x">
		<%= link_to '', "http://c0d3rgirl.com", :alt => "c0d3rgirl", :class => "element c0d3rgirl", :target => "_blank" %>
		<hr class="y">
		<%= link_to '', "http://startupheadlinegenerator.com", :alt => "Startup Headline Generator", :class => "element startupheadline", :target => "_blank" %>
		<hr class="x">
		<%= link_to '', "http://hauteornot.herokuapp.com", :alt => "Haute or Not", :class => "element hauteornot", :target => "_blank" %>
		<hr class="y">
		<span class="element spacer"></span>

	</div>
	
	<div class="social">
		<%= link_to '', "", :alt => "", :class => "", :target => "_blank" %>
		<%= link_to '', "", :alt => "", :class => "", :target => "_blank" %>
		<%= link_to '', "", :alt => "", :class => "", :target => "_blank" %>
		<%= link_to '', "", :alt => "", :class => "", :target => "_blank" %>
	</div>

</div>

app/views/pages/index.html.erb
<div class="lines"></div>